[2024-07-26T06:29:49.258+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-26T06:29:49.269+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 8_postgres_to_s3_dag.py.postgres_to_s3 scheduled__2024-07-25T00:00:00+00:00 [queued]>
[2024-07-26T06:29:49.272+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 8_postgres_to_s3_dag.py.postgres_to_s3 scheduled__2024-07-25T00:00:00+00:00 [queued]>
[2024-07-26T06:29:49.272+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 6
[2024-07-26T06:29:49.276+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-07-25 00:00:00+00:00
[2024-07-26T06:29:49.278+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=914) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-26T06:29:49.279+0000] {standard_task_runner.py:64} INFO - Started process 915 to run task
[2024-07-26T06:29:49.279+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '8_postgres_to_s3_dag.py', 'postgres_to_s3', 'scheduled__2024-07-25T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/8_postgres_to_s3_dag.py', '--cfg-path', '/tmp/tmph7hqlo60']
[2024-07-26T06:29:49.280+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask postgres_to_s3
[2024-07-26T06:29:49.295+0000] {task_command.py:426} INFO - Running <TaskInstance: 8_postgres_to_s3_dag.py.postgres_to_s3 scheduled__2024-07-25T00:00:00+00:00 [running]> on host ecd5bbc03de3
[2024-07-26T06:29:49.330+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='8_postgres_to_s3_dag.py' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T00:00:00+00:00'
[2024-07-26T06:29:49.330+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-26T06:29:49.340+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-07-26T06:29:49.348+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-26T06:29:49.349+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/8_postgres_to_s3_dag.py", line 31, in postgres_to_s3
    logging.log("Saved orders data into text file get_orders.txt.")
TypeError: log() missing 1 required positional argument: 'msg'
[2024-07-26T06:29:49.353+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=8_postgres_to_s3_dag.py, task_id=postgres_to_s3, run_id=scheduled__2024-07-25T00:00:00+00:00, execution_date=20240725T000000, start_date=20240726T062949, end_date=20240726T062949
[2024-07-26T06:29:49.357+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task postgres_to_s3 (log() missing 1 required positional argument: 'msg'; 915)
[2024-07-26T06:29:49.379+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-26T06:29:49.385+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-26T06:29:49.386+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
