[2024-07-26T06:31:07.146+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-26T06:31:07.160+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 8_postgres_to_s3_dag.py.postgres_to_s3 manual__2024-07-26T06:29:05.309727+00:00 [queued]>
[2024-07-26T06:31:07.163+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 8_postgres_to_s3_dag.py.postgres_to_s3 manual__2024-07-26T06:29:05.309727+00:00 [queued]>
[2024-07-26T06:31:07.163+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-07-26T06:31:07.168+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-07-26 06:29:05.309727+00:00
[2024-07-26T06:31:07.171+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=943) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-26T06:31:07.171+0000] {standard_task_runner.py:64} INFO - Started process 944 to run task
[2024-07-26T06:31:07.171+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '8_postgres_to_s3_dag.py', 'postgres_to_s3', 'manual__2024-07-26T06:29:05.309727+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/8_postgres_to_s3_dag.py', '--cfg-path', '/tmp/tmpj_15sutn']
[2024-07-26T06:31:07.172+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask postgres_to_s3
[2024-07-26T06:31:07.191+0000] {task_command.py:426} INFO - Running <TaskInstance: 8_postgres_to_s3_dag.py.postgres_to_s3 manual__2024-07-26T06:29:05.309727+00:00 [running]> on host ecd5bbc03de3
[2024-07-26T06:31:07.234+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='8_postgres_to_s3_dag.py' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-26T06:29:05.309727+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-26T06:29:05.309727+00:00'
[2024-07-26T06:31:07.235+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-26T06:31:07.246+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-07-26T06:31:07.260+0000] {8_postgres_to_s3_dag.py:31} INFO - Saved orders data into text file get_orders.txt.
[2024-07-26T06:31:07.260+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-26T06:31:07.262+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-26T06:31:07.273+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=8_postgres_to_s3_dag.py, task_id=postgres_to_s3, run_id=manual__2024-07-26T06:29:05.309727+00:00, execution_date=20240726T062905, start_date=20240726T063107, end_date=20240726T063107
[2024-07-26T06:31:07.314+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-26T06:31:07.321+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-26T06:31:07.321+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
