[2024-07-26T06:30:33.504+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-26T06:30:33.515+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 8_postgres_to_s3_dag.py.postgres_to_s3 manual__2024-07-26T06:28:31.770960+00:00 [queued]>
[2024-07-26T06:30:33.517+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 8_postgres_to_s3_dag.py.postgres_to_s3 manual__2024-07-26T06:28:31.770960+00:00 [queued]>
[2024-07-26T06:30:33.517+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-07-26T06:30:33.521+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-07-26 06:28:31.770960+00:00
[2024-07-26T06:30:33.523+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=934) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-26T06:30:33.524+0000] {standard_task_runner.py:64} INFO - Started process 935 to run task
[2024-07-26T06:30:33.524+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '8_postgres_to_s3_dag.py', 'postgres_to_s3', 'manual__2024-07-26T06:28:31.770960+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/8_postgres_to_s3_dag.py', '--cfg-path', '/tmp/tmpzw4wk6sz']
[2024-07-26T06:30:33.524+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask postgres_to_s3
[2024-07-26T06:30:33.538+0000] {task_command.py:426} INFO - Running <TaskInstance: 8_postgres_to_s3_dag.py.postgres_to_s3 manual__2024-07-26T06:28:31.770960+00:00 [running]> on host ecd5bbc03de3
[2024-07-26T06:30:33.566+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='8_postgres_to_s3_dag.py' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-26T06:28:31.770960+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-26T06:28:31.770960+00:00'
[2024-07-26T06:30:33.566+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-26T06:30:33.576+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-07-26T06:30:33.585+0000] {8_postgres_to_s3_dag.py:31} INFO - Saved orders data into text file get_orders.txt.
[2024-07-26T06:30:33.585+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-26T06:30:33.585+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-26T06:30:33.588+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=8_postgres_to_s3_dag.py, task_id=postgres_to_s3, run_id=manual__2024-07-26T06:28:31.770960+00:00, execution_date=20240726T062831, start_date=20240726T063033, end_date=20240726T063033
[2024-07-26T06:30:33.623+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-26T06:30:33.640+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-26T06:30:33.641+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
